// source: api.pdd.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.pddpb.GoodsPromotionUrl', null, global);
goog.exportSymbol('proto.pddpb.GoodsPromotionUrlGenerateResponse', null, global);
goog.exportSymbol('proto.pddpb.PromotionByURLRequest', null, global);
goog.exportSymbol('proto.pddpb.PromotionByURLResponse', null, global);
goog.exportSymbol('proto.pddpb.QQAppInfo', null, global);
goog.exportSymbol('proto.pddpb.WeAppInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pddpb.QQAppInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pddpb.QQAppInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pddpb.QQAppInfo.displayName = 'proto.pddpb.QQAppInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pddpb.WeAppInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pddpb.WeAppInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pddpb.WeAppInfo.displayName = 'proto.pddpb.WeAppInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pddpb.GoodsPromotionUrl = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pddpb.GoodsPromotionUrl, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pddpb.GoodsPromotionUrl.displayName = 'proto.pddpb.GoodsPromotionUrl';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pddpb.GoodsPromotionUrlGenerateResponse.repeatedFields_, null);
};
goog.inherits(proto.pddpb.GoodsPromotionUrlGenerateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pddpb.GoodsPromotionUrlGenerateResponse.displayName = 'proto.pddpb.GoodsPromotionUrlGenerateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pddpb.PromotionByURLRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pddpb.PromotionByURLRequest.repeatedFields_, null);
};
goog.inherits(proto.pddpb.PromotionByURLRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pddpb.PromotionByURLRequest.displayName = 'proto.pddpb.PromotionByURLRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pddpb.PromotionByURLResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pddpb.PromotionByURLResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pddpb.PromotionByURLResponse.displayName = 'proto.pddpb.PromotionByURLResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pddpb.QQAppInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.pddpb.QQAppInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pddpb.QQAppInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.QQAppInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    appId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bannerUrl: jspb.Message.getFieldWithDefault(msg, 2, ""),
    desc: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pagePath: jspb.Message.getFieldWithDefault(msg, 4, ""),
    qqAppIconUrl: jspb.Message.getFieldWithDefault(msg, 5, ""),
    sourceDisplayName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    title: jspb.Message.getFieldWithDefault(msg, 7, ""),
    userName: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pddpb.QQAppInfo}
 */
proto.pddpb.QQAppInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pddpb.QQAppInfo;
  return proto.pddpb.QQAppInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pddpb.QQAppInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pddpb.QQAppInfo}
 */
proto.pddpb.QQAppInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBannerUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDesc(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPagePath(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setQqAppIconUrl(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceDisplayName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pddpb.QQAppInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pddpb.QQAppInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pddpb.QQAppInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.QQAppInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBannerUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDesc();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPagePath();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getQqAppIconUrl();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSourceDisplayName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getUserName();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string app_id = 1;
 * @return {string}
 */
proto.pddpb.QQAppInfo.prototype.getAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.QQAppInfo} returns this
 */
proto.pddpb.QQAppInfo.prototype.setAppId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string banner_url = 2;
 * @return {string}
 */
proto.pddpb.QQAppInfo.prototype.getBannerUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.QQAppInfo} returns this
 */
proto.pddpb.QQAppInfo.prototype.setBannerUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string desc = 3;
 * @return {string}
 */
proto.pddpb.QQAppInfo.prototype.getDesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.QQAppInfo} returns this
 */
proto.pddpb.QQAppInfo.prototype.setDesc = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string page_path = 4;
 * @return {string}
 */
proto.pddpb.QQAppInfo.prototype.getPagePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.QQAppInfo} returns this
 */
proto.pddpb.QQAppInfo.prototype.setPagePath = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string qq_app_icon_url = 5;
 * @return {string}
 */
proto.pddpb.QQAppInfo.prototype.getQqAppIconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.QQAppInfo} returns this
 */
proto.pddpb.QQAppInfo.prototype.setQqAppIconUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string source_display_name = 6;
 * @return {string}
 */
proto.pddpb.QQAppInfo.prototype.getSourceDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.QQAppInfo} returns this
 */
proto.pddpb.QQAppInfo.prototype.setSourceDisplayName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string title = 7;
 * @return {string}
 */
proto.pddpb.QQAppInfo.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.QQAppInfo} returns this
 */
proto.pddpb.QQAppInfo.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string user_name = 8;
 * @return {string}
 */
proto.pddpb.QQAppInfo.prototype.getUserName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.QQAppInfo} returns this
 */
proto.pddpb.QQAppInfo.prototype.setUserName = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pddpb.WeAppInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.pddpb.WeAppInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pddpb.WeAppInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.WeAppInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    appId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bannerUrl: jspb.Message.getFieldWithDefault(msg, 2, ""),
    desc: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pagePath: jspb.Message.getFieldWithDefault(msg, 4, ""),
    weAppIconUrl: jspb.Message.getFieldWithDefault(msg, 5, ""),
    sourceDisplayName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    title: jspb.Message.getFieldWithDefault(msg, 7, ""),
    userName: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pddpb.WeAppInfo}
 */
proto.pddpb.WeAppInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pddpb.WeAppInfo;
  return proto.pddpb.WeAppInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pddpb.WeAppInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pddpb.WeAppInfo}
 */
proto.pddpb.WeAppInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setBannerUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDesc(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPagePath(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setWeAppIconUrl(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSourceDisplayName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pddpb.WeAppInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pddpb.WeAppInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pddpb.WeAppInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.WeAppInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBannerUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDesc();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPagePath();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getWeAppIconUrl();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSourceDisplayName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getUserName();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string app_id = 1;
 * @return {string}
 */
proto.pddpb.WeAppInfo.prototype.getAppId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.WeAppInfo} returns this
 */
proto.pddpb.WeAppInfo.prototype.setAppId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string banner_url = 2;
 * @return {string}
 */
proto.pddpb.WeAppInfo.prototype.getBannerUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.WeAppInfo} returns this
 */
proto.pddpb.WeAppInfo.prototype.setBannerUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string desc = 3;
 * @return {string}
 */
proto.pddpb.WeAppInfo.prototype.getDesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.WeAppInfo} returns this
 */
proto.pddpb.WeAppInfo.prototype.setDesc = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string page_path = 4;
 * @return {string}
 */
proto.pddpb.WeAppInfo.prototype.getPagePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.WeAppInfo} returns this
 */
proto.pddpb.WeAppInfo.prototype.setPagePath = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string we_app_icon_url = 5;
 * @return {string}
 */
proto.pddpb.WeAppInfo.prototype.getWeAppIconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.WeAppInfo} returns this
 */
proto.pddpb.WeAppInfo.prototype.setWeAppIconUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string source_display_name = 6;
 * @return {string}
 */
proto.pddpb.WeAppInfo.prototype.getSourceDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.WeAppInfo} returns this
 */
proto.pddpb.WeAppInfo.prototype.setSourceDisplayName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string title = 7;
 * @return {string}
 */
proto.pddpb.WeAppInfo.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.WeAppInfo} returns this
 */
proto.pddpb.WeAppInfo.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string user_name = 8;
 * @return {string}
 */
proto.pddpb.WeAppInfo.prototype.getUserName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.WeAppInfo} returns this
 */
proto.pddpb.WeAppInfo.prototype.setUserName = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pddpb.GoodsPromotionUrl.prototype.toObject = function(opt_includeInstance) {
  return proto.pddpb.GoodsPromotionUrl.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pddpb.GoodsPromotionUrl} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.GoodsPromotionUrl.toObject = function(includeInstance, msg) {
  var f, obj = {
    mobileShortUrl: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mobileUrl: jspb.Message.getFieldWithDefault(msg, 2, ""),
    qqAppInfo: (f = msg.getQqAppInfo()) && proto.pddpb.QQAppInfo.toObject(includeInstance, f),
    schemaUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    shortUrl: jspb.Message.getFieldWithDefault(msg, 5, ""),
    url: jspb.Message.getFieldWithDefault(msg, 6, ""),
    weAppInfo: (f = msg.getWeAppInfo()) && proto.pddpb.WeAppInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pddpb.GoodsPromotionUrl}
 */
proto.pddpb.GoodsPromotionUrl.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pddpb.GoodsPromotionUrl;
  return proto.pddpb.GoodsPromotionUrl.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pddpb.GoodsPromotionUrl} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pddpb.GoodsPromotionUrl}
 */
proto.pddpb.GoodsPromotionUrl.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMobileShortUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMobileUrl(value);
      break;
    case 3:
      var value = new proto.pddpb.QQAppInfo;
      reader.readMessage(value,proto.pddpb.QQAppInfo.deserializeBinaryFromReader);
      msg.setQqAppInfo(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSchemaUrl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setShortUrl(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 7:
      var value = new proto.pddpb.WeAppInfo;
      reader.readMessage(value,proto.pddpb.WeAppInfo.deserializeBinaryFromReader);
      msg.setWeAppInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pddpb.GoodsPromotionUrl.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pddpb.GoodsPromotionUrl.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pddpb.GoodsPromotionUrl} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.GoodsPromotionUrl.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMobileShortUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMobileUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getQqAppInfo();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.pddpb.QQAppInfo.serializeBinaryToWriter
    );
  }
  f = message.getSchemaUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getShortUrl();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getWeAppInfo();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.pddpb.WeAppInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string mobile_short_url = 1;
 * @return {string}
 */
proto.pddpb.GoodsPromotionUrl.prototype.getMobileShortUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
 */
proto.pddpb.GoodsPromotionUrl.prototype.setMobileShortUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string mobile_url = 2;
 * @return {string}
 */
proto.pddpb.GoodsPromotionUrl.prototype.getMobileUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
 */
proto.pddpb.GoodsPromotionUrl.prototype.setMobileUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional QQAppInfo qq_app_info = 3;
 * @return {?proto.pddpb.QQAppInfo}
 */
proto.pddpb.GoodsPromotionUrl.prototype.getQqAppInfo = function() {
  return /** @type{?proto.pddpb.QQAppInfo} */ (
    jspb.Message.getWrapperField(this, proto.pddpb.QQAppInfo, 3));
};


/**
 * @param {?proto.pddpb.QQAppInfo|undefined} value
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
*/
proto.pddpb.GoodsPromotionUrl.prototype.setQqAppInfo = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
 */
proto.pddpb.GoodsPromotionUrl.prototype.clearQqAppInfo = function() {
  return this.setQqAppInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.GoodsPromotionUrl.prototype.hasQqAppInfo = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string schema_url = 4;
 * @return {string}
 */
proto.pddpb.GoodsPromotionUrl.prototype.getSchemaUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
 */
proto.pddpb.GoodsPromotionUrl.prototype.setSchemaUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string short_url = 5;
 * @return {string}
 */
proto.pddpb.GoodsPromotionUrl.prototype.getShortUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
 */
proto.pddpb.GoodsPromotionUrl.prototype.setShortUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string url = 6;
 * @return {string}
 */
proto.pddpb.GoodsPromotionUrl.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
 */
proto.pddpb.GoodsPromotionUrl.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional WeAppInfo we_app_info = 7;
 * @return {?proto.pddpb.WeAppInfo}
 */
proto.pddpb.GoodsPromotionUrl.prototype.getWeAppInfo = function() {
  return /** @type{?proto.pddpb.WeAppInfo} */ (
    jspb.Message.getWrapperField(this, proto.pddpb.WeAppInfo, 7));
};


/**
 * @param {?proto.pddpb.WeAppInfo|undefined} value
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
*/
proto.pddpb.GoodsPromotionUrl.prototype.setWeAppInfo = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pddpb.GoodsPromotionUrl} returns this
 */
proto.pddpb.GoodsPromotionUrl.prototype.clearWeAppInfo = function() {
  return this.setWeAppInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.GoodsPromotionUrl.prototype.hasWeAppInfo = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pddpb.GoodsPromotionUrlGenerateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pddpb.GoodsPromotionUrlGenerateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    goodsPromotionUrlListList: jspb.Message.toObjectList(msg.getGoodsPromotionUrlListList(),
    proto.pddpb.GoodsPromotionUrl.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pddpb.GoodsPromotionUrlGenerateResponse}
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pddpb.GoodsPromotionUrlGenerateResponse;
  return proto.pddpb.GoodsPromotionUrlGenerateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pddpb.GoodsPromotionUrlGenerateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pddpb.GoodsPromotionUrlGenerateResponse}
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pddpb.GoodsPromotionUrl;
      reader.readMessage(value,proto.pddpb.GoodsPromotionUrl.deserializeBinaryFromReader);
      msg.addGoodsPromotionUrlList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pddpb.GoodsPromotionUrlGenerateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pddpb.GoodsPromotionUrlGenerateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGoodsPromotionUrlListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pddpb.GoodsPromotionUrl.serializeBinaryToWriter
    );
  }
};


/**
 * repeated GoodsPromotionUrl goods_promotion_url_list = 1;
 * @return {!Array<!proto.pddpb.GoodsPromotionUrl>}
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.prototype.getGoodsPromotionUrlListList = function() {
  return /** @type{!Array<!proto.pddpb.GoodsPromotionUrl>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pddpb.GoodsPromotionUrl, 1));
};


/**
 * @param {!Array<!proto.pddpb.GoodsPromotionUrl>} value
 * @return {!proto.pddpb.GoodsPromotionUrlGenerateResponse} returns this
*/
proto.pddpb.GoodsPromotionUrlGenerateResponse.prototype.setGoodsPromotionUrlListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pddpb.GoodsPromotionUrl=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pddpb.GoodsPromotionUrl}
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.prototype.addGoodsPromotionUrlList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pddpb.GoodsPromotionUrl, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pddpb.GoodsPromotionUrlGenerateResponse} returns this
 */
proto.pddpb.GoodsPromotionUrlGenerateResponse.prototype.clearGoodsPromotionUrlListList = function() {
  return this.setGoodsPromotionUrlListList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pddpb.PromotionByURLRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pddpb.PromotionByURLRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pddpb.PromotionByURLRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pddpb.PromotionByURLRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.PromotionByURLRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    goodsSignListList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    cashGiftId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    cashGiftName: jspb.Message.getFieldWithDefault(msg, 7, ""),
    customParameters: jspb.Message.getFieldWithDefault(msg, 8, ""),
    generateAuthorityUrl: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    generateMallCollectCoupon: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    generateQqApp: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
    generateSchemaUrl: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    generateShortUrl: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
    generateWeApp: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
    materialId: jspb.Message.getFieldWithDefault(msg, 15, ""),
    multiGroup: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
    searchId: jspb.Message.getFieldWithDefault(msg, 17, ""),
    zsDuoId: jspb.Message.getFieldWithDefault(msg, 18, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pddpb.PromotionByURLRequest}
 */
proto.pddpb.PromotionByURLRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pddpb.PromotionByURLRequest;
  return proto.pddpb.PromotionByURLRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pddpb.PromotionByURLRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pddpb.PromotionByURLRequest}
 */
proto.pddpb.PromotionByURLRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addGoodsSignList(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCashGiftId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCashGiftName(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomParameters(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGenerateAuthorityUrl(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGenerateMallCollectCoupon(value);
      break;
    case 11:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGenerateQqApp(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGenerateSchemaUrl(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGenerateShortUrl(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setGenerateWeApp(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaterialId(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMultiGroup(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearchId(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setZsDuoId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pddpb.PromotionByURLRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pddpb.PromotionByURLRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pddpb.PromotionByURLRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.PromotionByURLRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGoodsSignListList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeBool(
      9,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 10));
  if (f != null) {
    writer.writeBool(
      10,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 11));
  if (f != null) {
    writer.writeBool(
      11,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 12));
  if (f != null) {
    writer.writeBool(
      12,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 13));
  if (f != null) {
    writer.writeBool(
      13,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 14));
  if (f != null) {
    writer.writeBool(
      14,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 15));
  if (f != null) {
    writer.writeString(
      15,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 16));
  if (f != null) {
    writer.writeBool(
      16,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeString(
      17,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 18));
  if (f != null) {
    writer.writeUint64(
      18,
      f
    );
  }
};


/**
 * optional string p_id = 1;
 * @return {string}
 */
proto.pddpb.PromotionByURLRequest.prototype.getPId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setPId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string goods_sign_list = 2;
 * @return {!Array<string>}
 */
proto.pddpb.PromotionByURLRequest.prototype.getGoodsSignListList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setGoodsSignListList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.addGoodsSignList = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearGoodsSignListList = function() {
  return this.setGoodsSignListList([]);
};


/**
 * optional uint64 cash_gift_id = 6;
 * @return {number}
 */
proto.pddpb.PromotionByURLRequest.prototype.getCashGiftId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setCashGiftId = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearCashGiftId = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasCashGiftId = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string cash_gift_name = 7;
 * @return {string}
 */
proto.pddpb.PromotionByURLRequest.prototype.getCashGiftName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setCashGiftName = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearCashGiftName = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasCashGiftName = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string custom_parameters = 8;
 * @return {string}
 */
proto.pddpb.PromotionByURLRequest.prototype.getCustomParameters = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setCustomParameters = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearCustomParameters = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasCustomParameters = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bool generate_authority_url = 9;
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.getGenerateAuthorityUrl = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setGenerateAuthorityUrl = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearGenerateAuthorityUrl = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasGenerateAuthorityUrl = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional bool generate_mall_collect_coupon = 10;
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.getGenerateMallCollectCoupon = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setGenerateMallCollectCoupon = function(value) {
  return jspb.Message.setField(this, 10, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearGenerateMallCollectCoupon = function() {
  return jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasGenerateMallCollectCoupon = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional bool generate_qq_app = 11;
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.getGenerateQqApp = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setGenerateQqApp = function(value) {
  return jspb.Message.setField(this, 11, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearGenerateQqApp = function() {
  return jspb.Message.setField(this, 11, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasGenerateQqApp = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional bool generate_schema_url = 12;
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.getGenerateSchemaUrl = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setGenerateSchemaUrl = function(value) {
  return jspb.Message.setField(this, 12, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearGenerateSchemaUrl = function() {
  return jspb.Message.setField(this, 12, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasGenerateSchemaUrl = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional bool generate_short_url = 13;
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.getGenerateShortUrl = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setGenerateShortUrl = function(value) {
  return jspb.Message.setField(this, 13, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearGenerateShortUrl = function() {
  return jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasGenerateShortUrl = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bool generate_we_app = 14;
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.getGenerateWeApp = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setGenerateWeApp = function(value) {
  return jspb.Message.setField(this, 14, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearGenerateWeApp = function() {
  return jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasGenerateWeApp = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional string material_id = 15;
 * @return {string}
 */
proto.pddpb.PromotionByURLRequest.prototype.getMaterialId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setMaterialId = function(value) {
  return jspb.Message.setField(this, 15, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearMaterialId = function() {
  return jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasMaterialId = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional bool multi_group = 16;
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.getMultiGroup = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setMultiGroup = function(value) {
  return jspb.Message.setField(this, 16, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearMultiGroup = function() {
  return jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasMultiGroup = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional string search_id = 17;
 * @return {string}
 */
proto.pddpb.PromotionByURLRequest.prototype.getSearchId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setSearchId = function(value) {
  return jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearSearchId = function() {
  return jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasSearchId = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional uint64 zs_duo_id = 18;
 * @return {number}
 */
proto.pddpb.PromotionByURLRequest.prototype.getZsDuoId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.setZsDuoId = function(value) {
  return jspb.Message.setField(this, 18, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.pddpb.PromotionByURLRequest} returns this
 */
proto.pddpb.PromotionByURLRequest.prototype.clearZsDuoId = function() {
  return jspb.Message.setField(this, 18, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLRequest.prototype.hasZsDuoId = function() {
  return jspb.Message.getField(this, 18) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pddpb.PromotionByURLResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pddpb.PromotionByURLResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pddpb.PromotionByURLResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.PromotionByURLResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    goodsPromotionUrlGenerateResponse: (f = msg.getGoodsPromotionUrlGenerateResponse()) && proto.pddpb.GoodsPromotionUrlGenerateResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pddpb.PromotionByURLResponse}
 */
proto.pddpb.PromotionByURLResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pddpb.PromotionByURLResponse;
  return proto.pddpb.PromotionByURLResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pddpb.PromotionByURLResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pddpb.PromotionByURLResponse}
 */
proto.pddpb.PromotionByURLResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pddpb.GoodsPromotionUrlGenerateResponse;
      reader.readMessage(value,proto.pddpb.GoodsPromotionUrlGenerateResponse.deserializeBinaryFromReader);
      msg.setGoodsPromotionUrlGenerateResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pddpb.PromotionByURLResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pddpb.PromotionByURLResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pddpb.PromotionByURLResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pddpb.PromotionByURLResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGoodsPromotionUrlGenerateResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.pddpb.GoodsPromotionUrlGenerateResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional GoodsPromotionUrlGenerateResponse goods_promotion_url_generate_response = 1;
 * @return {?proto.pddpb.GoodsPromotionUrlGenerateResponse}
 */
proto.pddpb.PromotionByURLResponse.prototype.getGoodsPromotionUrlGenerateResponse = function() {
  return /** @type{?proto.pddpb.GoodsPromotionUrlGenerateResponse} */ (
    jspb.Message.getWrapperField(this, proto.pddpb.GoodsPromotionUrlGenerateResponse, 1));
};


/**
 * @param {?proto.pddpb.GoodsPromotionUrlGenerateResponse|undefined} value
 * @return {!proto.pddpb.PromotionByURLResponse} returns this
*/
proto.pddpb.PromotionByURLResponse.prototype.setGoodsPromotionUrlGenerateResponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pddpb.PromotionByURLResponse} returns this
 */
proto.pddpb.PromotionByURLResponse.prototype.clearGoodsPromotionUrlGenerateResponse = function() {
  return this.setGoodsPromotionUrlGenerateResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pddpb.PromotionByURLResponse.prototype.hasGoodsPromotionUrlGenerateResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.pddpb);
