// source: api.jd.ddx.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.jdpb.CommissionInfo', null, global);
goog.exportSymbol('proto.jdpb.CouponInfo', null, global);
goog.exportSymbol('proto.jdpb.ImageInfo', null, global);
goog.exportSymbol('proto.jdpb.ImageURL', null, global);
goog.exportSymbol('proto.jdpb.PinGouInfo', null, global);
goog.exportSymbol('proto.jdpb.PriceInfo', null, global);
goog.exportSymbol('proto.jdpb.PromotedData', null, global);
goog.exportSymbol('proto.jdpb.PromotionByUnionIDRequest', null, global);
goog.exportSymbol('proto.jdpb.PromotionByUnionIDResponse', null, global);
goog.exportSymbol('proto.jdpb.ShopInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.CouponInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdpb.CouponInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.CouponInfo.displayName = 'proto.jdpb.CouponInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.CommissionInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdpb.CommissionInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.CommissionInfo.displayName = 'proto.jdpb.CommissionInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.ImageURL = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdpb.ImageURL, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.ImageURL.displayName = 'proto.jdpb.ImageURL';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.ImageInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jdpb.ImageInfo.repeatedFields_, null);
};
goog.inherits(proto.jdpb.ImageInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.ImageInfo.displayName = 'proto.jdpb.ImageInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.PriceInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdpb.PriceInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.PriceInfo.displayName = 'proto.jdpb.PriceInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.PinGouInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdpb.PinGouInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.PinGouInfo.displayName = 'proto.jdpb.PinGouInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.ShopInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdpb.ShopInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.ShopInfo.displayName = 'proto.jdpb.ShopInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.PromotedData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.jdpb.PromotedData.repeatedFields_, null);
};
goog.inherits(proto.jdpb.PromotedData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.PromotedData.displayName = 'proto.jdpb.PromotedData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.PromotionByUnionIDRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdpb.PromotionByUnionIDRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.PromotionByUnionIDRequest.displayName = 'proto.jdpb.PromotionByUnionIDRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.jdpb.PromotionByUnionIDResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.jdpb.PromotionByUnionIDResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.jdpb.PromotionByUnionIDResponse.displayName = 'proto.jdpb.PromotionByUnionIDResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.CouponInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.CouponInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.CouponInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.CouponInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    takeendtime: jspb.Message.getFieldWithDefault(msg, 1, 0),
    takebegintime: jspb.Message.getFieldWithDefault(msg, 2, 0),
    remainnum: jspb.Message.getFieldWithDefault(msg, 3, 0),
    yn: jspb.Message.getFieldWithDefault(msg, 4, ""),
    num: jspb.Message.getFieldWithDefault(msg, 5, 0),
    quota: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    link: jspb.Message.getFieldWithDefault(msg, 7, ""),
    discount: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    begintime: jspb.Message.getFieldWithDefault(msg, 9, 0),
    endtime: jspb.Message.getFieldWithDefault(msg, 10, 0),
    platform: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.CouponInfo}
 */
proto.jdpb.CouponInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.CouponInfo;
  return proto.jdpb.CouponInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.CouponInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.CouponInfo}
 */
proto.jdpb.CouponInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTakeendtime(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTakebegintime(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRemainnum(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setYn(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setNum(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setQuota(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLink(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDiscount(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setBegintime(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEndtime(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatform(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.CouponInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.CouponInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.CouponInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.CouponInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTakeendtime();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getTakebegintime();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getRemainnum();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getYn();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNum();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getQuota();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getLink();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getDiscount();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getBegintime();
  if (f !== 0) {
    writer.writeUint64(
      9,
      f
    );
  }
  f = message.getEndtime();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
  f = message.getPlatform();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional uint64 takeEndTime = 1;
 * @return {number}
 */
proto.jdpb.CouponInfo.prototype.getTakeendtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setTakeendtime = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 takeBeginTime = 2;
 * @return {number}
 */
proto.jdpb.CouponInfo.prototype.getTakebegintime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setTakebegintime = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 remainNum = 3;
 * @return {number}
 */
proto.jdpb.CouponInfo.prototype.getRemainnum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setRemainnum = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string yn = 4;
 * @return {string}
 */
proto.jdpb.CouponInfo.prototype.getYn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setYn = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional uint64 num = 5;
 * @return {number}
 */
proto.jdpb.CouponInfo.prototype.getNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setNum = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional double quota = 6;
 * @return {number}
 */
proto.jdpb.CouponInfo.prototype.getQuota = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setQuota = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional string link = 7;
 * @return {string}
 */
proto.jdpb.CouponInfo.prototype.getLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setLink = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional double discount = 8;
 * @return {number}
 */
proto.jdpb.CouponInfo.prototype.getDiscount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setDiscount = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional uint64 beginTime = 9;
 * @return {number}
 */
proto.jdpb.CouponInfo.prototype.getBegintime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setBegintime = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint64 endTime = 10;
 * @return {number}
 */
proto.jdpb.CouponInfo.prototype.getEndtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setEndtime = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string platform = 11;
 * @return {string}
 */
proto.jdpb.CouponInfo.prototype.getPlatform = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.CouponInfo} returns this
 */
proto.jdpb.CouponInfo.prototype.setPlatform = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.CommissionInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.CommissionInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.CommissionInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.CommissionInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    commission: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    commissionshare: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    couponcommission: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    pluscommissionshare: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    endtime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    starttime: jspb.Message.getFieldWithDefault(msg, 6, 0),
    islock: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.CommissionInfo}
 */
proto.jdpb.CommissionInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.CommissionInfo;
  return proto.jdpb.CommissionInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.CommissionInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.CommissionInfo}
 */
proto.jdpb.CommissionInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCommission(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCommissionshare(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCouponcommission(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPluscommissionshare(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setEndtime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setStarttime(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIslock(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.CommissionInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.CommissionInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.CommissionInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.CommissionInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommission();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getCommissionshare();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getCouponcommission();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getPluscommissionshare();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getEndtime();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = message.getStarttime();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getIslock();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
};


/**
 * optional double commission = 1;
 * @return {number}
 */
proto.jdpb.CommissionInfo.prototype.getCommission = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CommissionInfo} returns this
 */
proto.jdpb.CommissionInfo.prototype.setCommission = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double commissionShare = 2;
 * @return {number}
 */
proto.jdpb.CommissionInfo.prototype.getCommissionshare = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CommissionInfo} returns this
 */
proto.jdpb.CommissionInfo.prototype.setCommissionshare = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double couponCommission = 3;
 * @return {number}
 */
proto.jdpb.CommissionInfo.prototype.getCouponcommission = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CommissionInfo} returns this
 */
proto.jdpb.CommissionInfo.prototype.setCouponcommission = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double plusCommissionShare = 4;
 * @return {number}
 */
proto.jdpb.CommissionInfo.prototype.getPluscommissionshare = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CommissionInfo} returns this
 */
proto.jdpb.CommissionInfo.prototype.setPluscommissionshare = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional uint64 endTime = 5;
 * @return {number}
 */
proto.jdpb.CommissionInfo.prototype.getEndtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CommissionInfo} returns this
 */
proto.jdpb.CommissionInfo.prototype.setEndtime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint64 startTime = 6;
 * @return {number}
 */
proto.jdpb.CommissionInfo.prototype.getStarttime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CommissionInfo} returns this
 */
proto.jdpb.CommissionInfo.prototype.setStarttime = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 isLock = 7;
 * @return {number}
 */
proto.jdpb.CommissionInfo.prototype.getIslock = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.CommissionInfo} returns this
 */
proto.jdpb.CommissionInfo.prototype.setIslock = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.ImageURL.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.ImageURL.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.ImageURL} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.ImageURL.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.ImageURL}
 */
proto.jdpb.ImageURL.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.ImageURL;
  return proto.jdpb.ImageURL.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.ImageURL} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.ImageURL}
 */
proto.jdpb.ImageURL.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.ImageURL.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.ImageURL.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.ImageURL} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.ImageURL.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.jdpb.ImageURL.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.ImageURL} returns this
 */
proto.jdpb.ImageURL.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jdpb.ImageInfo.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.ImageInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.ImageInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.ImageInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.ImageInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    imagelistList: jspb.Message.toObjectList(msg.getImagelistList(),
    proto.jdpb.ImageURL.toObject, includeInstance),
    whiteimage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.ImageInfo}
 */
proto.jdpb.ImageInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.ImageInfo;
  return proto.jdpb.ImageInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.ImageInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.ImageInfo}
 */
proto.jdpb.ImageInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.jdpb.ImageURL;
      reader.readMessage(value,proto.jdpb.ImageURL.deserializeBinaryFromReader);
      msg.addImagelist(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWhiteimage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.ImageInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.ImageInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.ImageInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.ImageInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getImagelistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.jdpb.ImageURL.serializeBinaryToWriter
    );
  }
  f = message.getWhiteimage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * repeated ImageURL imageList = 1;
 * @return {!Array<!proto.jdpb.ImageURL>}
 */
proto.jdpb.ImageInfo.prototype.getImagelistList = function() {
  return /** @type{!Array<!proto.jdpb.ImageURL>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jdpb.ImageURL, 1));
};


/**
 * @param {!Array<!proto.jdpb.ImageURL>} value
 * @return {!proto.jdpb.ImageInfo} returns this
*/
proto.jdpb.ImageInfo.prototype.setImagelistList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.jdpb.ImageURL=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jdpb.ImageURL}
 */
proto.jdpb.ImageInfo.prototype.addImagelist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.jdpb.ImageURL, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jdpb.ImageInfo} returns this
 */
proto.jdpb.ImageInfo.prototype.clearImagelistList = function() {
  return this.setImagelistList([]);
};


/**
 * optional string whiteImage = 2;
 * @return {string}
 */
proto.jdpb.ImageInfo.prototype.getWhiteimage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.ImageInfo} returns this
 */
proto.jdpb.ImageInfo.prototype.setWhiteimage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.PriceInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.PriceInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.PriceInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PriceInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    historypriceday: jspb.Message.getFieldWithDefault(msg, 2, 0),
    lowestcouponprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    lowestprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    lowestpricetype: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.PriceInfo}
 */
proto.jdpb.PriceInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.PriceInfo;
  return proto.jdpb.PriceInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.PriceInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.PriceInfo}
 */
proto.jdpb.PriceInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHistorypriceday(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLowestcouponprice(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLowestprice(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLowestpricetype(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.PriceInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.PriceInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.PriceInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PriceInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getHistorypriceday();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getLowestprice();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getLowestpricetype();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional double price = 1;
 * @return {number}
 */
proto.jdpb.PriceInfo.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PriceInfo} returns this
 */
proto.jdpb.PriceInfo.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional int64 historyPriceDay = 2;
 * @return {number}
 */
proto.jdpb.PriceInfo.prototype.getHistorypriceday = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PriceInfo} returns this
 */
proto.jdpb.PriceInfo.prototype.setHistorypriceday = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional double lowestCouponPrice = 3;
 * @return {number}
 */
proto.jdpb.PriceInfo.prototype.getLowestcouponprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PriceInfo} returns this
 */
proto.jdpb.PriceInfo.prototype.setLowestcouponprice = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PriceInfo} returns this
 */
proto.jdpb.PriceInfo.prototype.clearLowestcouponprice = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PriceInfo.prototype.hasLowestcouponprice = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double lowestPrice = 4;
 * @return {number}
 */
proto.jdpb.PriceInfo.prototype.getLowestprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PriceInfo} returns this
 */
proto.jdpb.PriceInfo.prototype.setLowestprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int64 lowestPriceType = 5;
 * @return {number}
 */
proto.jdpb.PriceInfo.prototype.getLowestpricetype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PriceInfo} returns this
 */
proto.jdpb.PriceInfo.prototype.setLowestpricetype = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.PinGouInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.PinGouInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.PinGouInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PinGouInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    pingouprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    pingoutmcount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    pingouurl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pingoustarttime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    pingouendtime: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.PinGouInfo}
 */
proto.jdpb.PinGouInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.PinGouInfo;
  return proto.jdpb.PinGouInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.PinGouInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.PinGouInfo}
 */
proto.jdpb.PinGouInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPingouprice(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPingoutmcount(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPingouurl(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPingoustarttime(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPingouendtime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.PinGouInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.PinGouInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.PinGouInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PinGouInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPingouprice();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getPingoutmcount();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getPingouurl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPingoustarttime();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getPingouendtime();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
};


/**
 * optional double pingouPrice = 1;
 * @return {number}
 */
proto.jdpb.PinGouInfo.prototype.getPingouprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PinGouInfo} returns this
 */
proto.jdpb.PinGouInfo.prototype.setPingouprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional uint64 pingouTmCount = 2;
 * @return {number}
 */
proto.jdpb.PinGouInfo.prototype.getPingoutmcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PinGouInfo} returns this
 */
proto.jdpb.PinGouInfo.prototype.setPingoutmcount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string pingouUrl = 3;
 * @return {string}
 */
proto.jdpb.PinGouInfo.prototype.getPingouurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PinGouInfo} returns this
 */
proto.jdpb.PinGouInfo.prototype.setPingouurl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint64 pingouStartTime = 4;
 * @return {number}
 */
proto.jdpb.PinGouInfo.prototype.getPingoustarttime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PinGouInfo} returns this
 */
proto.jdpb.PinGouInfo.prototype.setPingoustarttime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint64 pingouEndTime = 5;
 * @return {number}
 */
proto.jdpb.PinGouInfo.prototype.getPingouendtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PinGouInfo} returns this
 */
proto.jdpb.PinGouInfo.prototype.setPingouendtime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.ShopInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.ShopInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.ShopInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.ShopInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    shopid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    shoplabel: jspb.Message.getFieldWithDefault(msg, 2, ""),
    shoplevel: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    shopname: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.ShopInfo}
 */
proto.jdpb.ShopInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.ShopInfo;
  return proto.jdpb.ShopInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.ShopInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.ShopInfo}
 */
proto.jdpb.ShopInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setShopid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setShoplabel(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setShoplevel(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setShopname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.ShopInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.ShopInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.ShopInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.ShopInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShopid();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getShoplabel();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getShoplevel();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getShopname();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional uint64 shopId = 1;
 * @return {number}
 */
proto.jdpb.ShopInfo.prototype.getShopid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.ShopInfo} returns this
 */
proto.jdpb.ShopInfo.prototype.setShopid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string shopLabel = 2;
 * @return {string}
 */
proto.jdpb.ShopInfo.prototype.getShoplabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.ShopInfo} returns this
 */
proto.jdpb.ShopInfo.prototype.setShoplabel = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double shopLevel = 3;
 * @return {number}
 */
proto.jdpb.ShopInfo.prototype.getShoplevel = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.ShopInfo} returns this
 */
proto.jdpb.ShopInfo.prototype.setShoplevel = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string shopName = 4;
 * @return {string}
 */
proto.jdpb.ShopInfo.prototype.getShopname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.ShopInfo} returns this
 */
proto.jdpb.ShopInfo.prototype.setShopname = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.jdpb.PromotedData.repeatedFields_ = [6,10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.PromotedData.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.PromotedData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.PromotedData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PromotedData.toObject = function(includeInstance, msg) {
  var f, obj = {
    shorturl: jspb.Message.getFieldWithDefault(msg, 1, ""),
    clickurl: jspb.Message.getFieldWithDefault(msg, 2, ""),
    jcommand: jspb.Message.getFieldWithDefault(msg, 3, ""),
    note: jspb.Message.getFieldWithDefault(msg, 4, ""),
    isCoupon: jspb.Message.getFieldWithDefault(msg, 5, 0),
    couponinfoList: jspb.Message.toObjectList(msg.getCouponinfoList(),
    proto.jdpb.CouponInfo.toObject, includeInstance),
    commissioninfo: (f = msg.getCommissioninfo()) && proto.jdpb.CommissionInfo.toObject(includeInstance, f),
    imageinfo: (f = msg.getImageinfo()) && proto.jdpb.ImageInfo.toObject(includeInstance, f),
    priceinfo: (f = msg.getPriceinfo()) && proto.jdpb.PriceInfo.toObject(includeInstance, f),
    pingouinfoList: jspb.Message.toObjectList(msg.getPingouinfoList(),
    proto.jdpb.PinGouInfo.toObject, includeInstance),
    shopinfo: (f = msg.getShopinfo()) && proto.jdpb.ShopInfo.toObject(includeInstance, f),
    skuid: jspb.Message.getFieldWithDefault(msg, 12, 0),
    skuname: jspb.Message.getFieldWithDefault(msg, 13, ""),
    owner: jspb.Message.getFieldWithDefault(msg, 14, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.PromotedData}
 */
proto.jdpb.PromotedData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.PromotedData;
  return proto.jdpb.PromotedData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.PromotedData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.PromotedData}
 */
proto.jdpb.PromotedData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setShorturl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClickurl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setJcommand(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIsCoupon(value);
      break;
    case 6:
      var value = new proto.jdpb.CouponInfo;
      reader.readMessage(value,proto.jdpb.CouponInfo.deserializeBinaryFromReader);
      msg.addCouponinfo(value);
      break;
    case 7:
      var value = new proto.jdpb.CommissionInfo;
      reader.readMessage(value,proto.jdpb.CommissionInfo.deserializeBinaryFromReader);
      msg.setCommissioninfo(value);
      break;
    case 8:
      var value = new proto.jdpb.ImageInfo;
      reader.readMessage(value,proto.jdpb.ImageInfo.deserializeBinaryFromReader);
      msg.setImageinfo(value);
      break;
    case 9:
      var value = new proto.jdpb.PriceInfo;
      reader.readMessage(value,proto.jdpb.PriceInfo.deserializeBinaryFromReader);
      msg.setPriceinfo(value);
      break;
    case 10:
      var value = new proto.jdpb.PinGouInfo;
      reader.readMessage(value,proto.jdpb.PinGouInfo.deserializeBinaryFromReader);
      msg.addPingouinfo(value);
      break;
    case 11:
      var value = new proto.jdpb.ShopInfo;
      reader.readMessage(value,proto.jdpb.ShopInfo.deserializeBinaryFromReader);
      msg.setShopinfo(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setSkuid(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkuname(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.PromotedData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.PromotedData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.PromotedData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PromotedData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getShorturl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getClickurl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getIsCoupon();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getCouponinfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.jdpb.CouponInfo.serializeBinaryToWriter
    );
  }
  f = message.getCommissioninfo();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.jdpb.CommissionInfo.serializeBinaryToWriter
    );
  }
  f = message.getImageinfo();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.jdpb.ImageInfo.serializeBinaryToWriter
    );
  }
  f = message.getPriceinfo();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.jdpb.PriceInfo.serializeBinaryToWriter
    );
  }
  f = message.getPingouinfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.jdpb.PinGouInfo.serializeBinaryToWriter
    );
  }
  f = message.getShopinfo();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.jdpb.ShopInfo.serializeBinaryToWriter
    );
  }
  f = message.getSkuid();
  if (f !== 0) {
    writer.writeUint64(
      12,
      f
    );
  }
  f = message.getSkuname();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getOwner();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
};


/**
 * optional string shortURL = 1;
 * @return {string}
 */
proto.jdpb.PromotedData.prototype.getShorturl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.setShorturl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string clickURL = 2;
 * @return {string}
 */
proto.jdpb.PromotedData.prototype.getClickurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.setClickurl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string jCommand = 3;
 * @return {string}
 */
proto.jdpb.PromotedData.prototype.getJcommand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.setJcommand = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.clearJcommand = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotedData.prototype.hasJcommand = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string note = 4;
 * @return {string}
 */
proto.jdpb.PromotedData.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.setNote = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 is_coupon = 5;
 * @return {number}
 */
proto.jdpb.PromotedData.prototype.getIsCoupon = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.setIsCoupon = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * repeated CouponInfo couponInfo = 6;
 * @return {!Array<!proto.jdpb.CouponInfo>}
 */
proto.jdpb.PromotedData.prototype.getCouponinfoList = function() {
  return /** @type{!Array<!proto.jdpb.CouponInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jdpb.CouponInfo, 6));
};


/**
 * @param {!Array<!proto.jdpb.CouponInfo>} value
 * @return {!proto.jdpb.PromotedData} returns this
*/
proto.jdpb.PromotedData.prototype.setCouponinfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.jdpb.CouponInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jdpb.CouponInfo}
 */
proto.jdpb.PromotedData.prototype.addCouponinfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.jdpb.CouponInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.clearCouponinfoList = function() {
  return this.setCouponinfoList([]);
};


/**
 * optional CommissionInfo commissionInfo = 7;
 * @return {?proto.jdpb.CommissionInfo}
 */
proto.jdpb.PromotedData.prototype.getCommissioninfo = function() {
  return /** @type{?proto.jdpb.CommissionInfo} */ (
    jspb.Message.getWrapperField(this, proto.jdpb.CommissionInfo, 7));
};


/**
 * @param {?proto.jdpb.CommissionInfo|undefined} value
 * @return {!proto.jdpb.PromotedData} returns this
*/
proto.jdpb.PromotedData.prototype.setCommissioninfo = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.clearCommissioninfo = function() {
  return this.setCommissioninfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotedData.prototype.hasCommissioninfo = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional ImageInfo imageInfo = 8;
 * @return {?proto.jdpb.ImageInfo}
 */
proto.jdpb.PromotedData.prototype.getImageinfo = function() {
  return /** @type{?proto.jdpb.ImageInfo} */ (
    jspb.Message.getWrapperField(this, proto.jdpb.ImageInfo, 8));
};


/**
 * @param {?proto.jdpb.ImageInfo|undefined} value
 * @return {!proto.jdpb.PromotedData} returns this
*/
proto.jdpb.PromotedData.prototype.setImageinfo = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.clearImageinfo = function() {
  return this.setImageinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotedData.prototype.hasImageinfo = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional PriceInfo priceInfo = 9;
 * @return {?proto.jdpb.PriceInfo}
 */
proto.jdpb.PromotedData.prototype.getPriceinfo = function() {
  return /** @type{?proto.jdpb.PriceInfo} */ (
    jspb.Message.getWrapperField(this, proto.jdpb.PriceInfo, 9));
};


/**
 * @param {?proto.jdpb.PriceInfo|undefined} value
 * @return {!proto.jdpb.PromotedData} returns this
*/
proto.jdpb.PromotedData.prototype.setPriceinfo = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.clearPriceinfo = function() {
  return this.setPriceinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotedData.prototype.hasPriceinfo = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated PinGouInfo pinGouInfo = 10;
 * @return {!Array<!proto.jdpb.PinGouInfo>}
 */
proto.jdpb.PromotedData.prototype.getPingouinfoList = function() {
  return /** @type{!Array<!proto.jdpb.PinGouInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.jdpb.PinGouInfo, 10));
};


/**
 * @param {!Array<!proto.jdpb.PinGouInfo>} value
 * @return {!proto.jdpb.PromotedData} returns this
*/
proto.jdpb.PromotedData.prototype.setPingouinfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.jdpb.PinGouInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.jdpb.PinGouInfo}
 */
proto.jdpb.PromotedData.prototype.addPingouinfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.jdpb.PinGouInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.clearPingouinfoList = function() {
  return this.setPingouinfoList([]);
};


/**
 * optional ShopInfo shopInfo = 11;
 * @return {?proto.jdpb.ShopInfo}
 */
proto.jdpb.PromotedData.prototype.getShopinfo = function() {
  return /** @type{?proto.jdpb.ShopInfo} */ (
    jspb.Message.getWrapperField(this, proto.jdpb.ShopInfo, 11));
};


/**
 * @param {?proto.jdpb.ShopInfo|undefined} value
 * @return {!proto.jdpb.PromotedData} returns this
*/
proto.jdpb.PromotedData.prototype.setShopinfo = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.clearShopinfo = function() {
  return this.setShopinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotedData.prototype.hasShopinfo = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional uint64 skuId = 12;
 * @return {number}
 */
proto.jdpb.PromotedData.prototype.getSkuid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.setSkuid = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string skuName = 13;
 * @return {string}
 */
proto.jdpb.PromotedData.prototype.getSkuname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.setSkuname = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string owner = 14;
 * @return {string}
 */
proto.jdpb.PromotedData.prototype.getOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotedData} returns this
 */
proto.jdpb.PromotedData.prototype.setOwner = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.PromotionByUnionIDRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.PromotionByUnionIDRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PromotionByUnionIDRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    materialid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    unionid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    autosearch: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    positionid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    couponurl: jspb.Message.getFieldWithDefault(msg, 6, ""),
    chaintype: jspb.Message.getFieldWithDefault(msg, 7, 0),
    subunionid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    giftcouponkey: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.PromotionByUnionIDRequest}
 */
proto.jdpb.PromotionByUnionIDRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.PromotionByUnionIDRequest;
  return proto.jdpb.PromotionByUnionIDRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.PromotionByUnionIDRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.PromotionByUnionIDRequest}
 */
proto.jdpb.PromotionByUnionIDRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaterialid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setUnionid(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAutosearch(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setPositionid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCouponurl(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setChaintype(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubunionid(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setGiftcouponkey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.PromotionByUnionIDRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.PromotionByUnionIDRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PromotionByUnionIDRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaterialid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUnionid();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBool(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeUint64(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string materialId = 1;
 * @return {string}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getMaterialid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setMaterialid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint64 unionId = 2;
 * @return {number}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getUnionid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setUnionid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional bool autoSearch = 3;
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getAutosearch = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setAutosearch = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.clearAutosearch = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.hasAutosearch = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 type = 4;
 * @return {number}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setType = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.clearType = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.hasType = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint64 positionId = 5;
 * @return {number}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getPositionid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setPositionid = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.clearPositionid = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.hasPositionid = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string couponUrl = 6;
 * @return {string}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getCouponurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setCouponurl = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.clearCouponurl = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.hasCouponurl = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional int64 chainType = 7;
 * @return {number}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getChaintype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setChaintype = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.clearChaintype = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.hasChaintype = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string subUnionId = 8;
 * @return {string}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getSubunionid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setSubunionid = function(value) {
  return jspb.Message.setField(this, 8, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.clearSubunionid = function() {
  return jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.hasSubunionid = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional string giftCouponKey = 9;
 * @return {string}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.getGiftcouponkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.setGiftcouponkey = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.jdpb.PromotionByUnionIDRequest} returns this
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.clearGiftcouponkey = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDRequest.prototype.hasGiftcouponkey = function() {
  return jspb.Message.getField(this, 9) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.jdpb.PromotionByUnionIDResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.jdpb.PromotionByUnionIDResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PromotionByUnionIDResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    code: jspb.Message.getFieldWithDefault(msg, 1, 0),
    msg: jspb.Message.getFieldWithDefault(msg, 2, ""),
    data: (f = msg.getData()) && proto.jdpb.PromotedData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.jdpb.PromotionByUnionIDResponse}
 */
proto.jdpb.PromotionByUnionIDResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.jdpb.PromotionByUnionIDResponse;
  return proto.jdpb.PromotionByUnionIDResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.jdpb.PromotionByUnionIDResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.jdpb.PromotionByUnionIDResponse}
 */
proto.jdpb.PromotionByUnionIDResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = new proto.jdpb.PromotedData;
      reader.readMessage(value,proto.jdpb.PromotedData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.jdpb.PromotionByUnionIDResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.jdpb.PromotionByUnionIDResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.jdpb.PromotionByUnionIDResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.jdpb.PromotedData.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 code = 1;
 * @return {number}
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.getCode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.jdpb.PromotionByUnionIDResponse} returns this
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.setCode = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.jdpb.PromotionByUnionIDResponse} returns this
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.setMsg = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional PromotedData data = 3;
 * @return {?proto.jdpb.PromotedData}
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.getData = function() {
  return /** @type{?proto.jdpb.PromotedData} */ (
    jspb.Message.getWrapperField(this, proto.jdpb.PromotedData, 3));
};


/**
 * @param {?proto.jdpb.PromotedData|undefined} value
 * @return {!proto.jdpb.PromotionByUnionIDResponse} returns this
*/
proto.jdpb.PromotionByUnionIDResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.jdpb.PromotionByUnionIDResponse} returns this
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.jdpb.PromotionByUnionIDResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.jdpb);
