// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: vendors.proto

package vendors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vendor int32

const (
	Vendor_UNKNOWN Vendor = 0
	Vendor_TB      Vendor = 1
	Vendor_JD      Vendor = 2
	Vendor_PDD     Vendor = 3
)

// Enum value maps for Vendor.
var (
	Vendor_name = map[int32]string{
		0: "UNKNOWN",
		1: "TB",
		2: "JD",
		3: "PDD",
	}
	Vendor_value = map[string]int32{
		"UNKNOWN": 0,
		"TB":      1,
		"JD":      2,
		"PDD":     3,
	}
)

func (x Vendor) Enum() *Vendor {
	p := new(Vendor)
	*p = x
	return p
}

func (x Vendor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Vendor) Descriptor() protoreflect.EnumDescriptor {
	return file_vendors_proto_enumTypes[0].Descriptor()
}

func (Vendor) Type() protoreflect.EnumType {
	return &file_vendors_proto_enumTypes[0]
}

func (x Vendor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Vendor.Descriptor instead.
func (Vendor) EnumDescriptor() ([]byte, []int) {
	return file_vendors_proto_rawDescGZIP(), []int{0}
}

var File_vendors_proto protoreflect.FileDescriptor

var file_vendors_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x2a, 0x2e, 0x0a, 0x06, 0x56, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x06, 0x0a, 0x02, 0x54, 0x42, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4a, 0x44, 0x10, 0x02, 0x12,
	0x07, 0x0a, 0x03, 0x50, 0x44, 0x44, 0x10, 0x03, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x76, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vendors_proto_rawDescOnce sync.Once
	file_vendors_proto_rawDescData = file_vendors_proto_rawDesc
)

func file_vendors_proto_rawDescGZIP() []byte {
	file_vendors_proto_rawDescOnce.Do(func() {
		file_vendors_proto_rawDescData = protoimpl.X.CompressGZIP(file_vendors_proto_rawDescData)
	})
	return file_vendors_proto_rawDescData
}

var file_vendors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vendors_proto_goTypes = []interface{}{
	(Vendor)(0), // 0: vendors.Vendor
}
var file_vendors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vendors_proto_init() }
func file_vendors_proto_init() {
	if File_vendors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vendors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vendors_proto_goTypes,
		DependencyIndexes: file_vendors_proto_depIdxs,
		EnumInfos:         file_vendors_proto_enumTypes,
	}.Build()
	File_vendors_proto = out.File
	file_vendors_proto_rawDesc = nil
	file_vendors_proto_goTypes = nil
	file_vendors_proto_depIdxs = nil
}
